const experiments = [
  {
    "id": "01",
    "sourceId": "01",
    "round": "round1",
    "roundLabel": "01 / 基准探索",
    "title": "经典空气喷绘",
    "prompt": "请创作一幅16:9宽幅城市绘画。固定场景：站在上海外滩中段的滨江步道，向东跨过黄浦江眺望陆家嘴；黄浦江占画面下方约三分之一，河面平静并有一艘白色渡轮从左向右行驶；东方明珠位于画面左侧三分之一，上海中心大厦为最高建筑并位于中右侧，金茂大厦与上海环球金融中心组成清晰的天际线；前景左下角保留少量外滩石栏杆；夏日18:50蓝调黄昏，薄云，城市灯光刚刚亮起。采用1980年代日本City Pop唱片封面常见的清爽城市度假插画语言：干净的空气喷绘渐变，青蓝天空、珊瑚粉地平线、奶油黄色灯光，清晰硬边轮廓，强烈但柔和的逆光，大面积留白，安静、通透、无人物的理想化城市空间，细腻丙烯颜料与插画板质感。不要复制任何具体艺术家的作品。保持建筑位置、镜头高度约1.6米、50mm视角和构图不变；不要增加棕榈树、海滩、游泳池、美国公路、人物特写、广告牌、可读文字、logo、水印、照片写实、3D渲染或拼贴。",
    "image": "images/01/chatgpt_1788061245928.png",
    "aspect": "landscape",
    "variant": null
  },
  {
    "id": "02",
    "sourceId": "02",
    "round": "round1",
    "roundLabel": "01 / 基准探索",
    "title": "高饱和商业插画",
    "prompt": "请创作一幅16:9宽幅城市绘画。固定场景：站在上海外滩中段的滨江步道，向东跨过黄浦江眺望陆家嘴；黄浦江占画面下方约三分之一，河面平静并有一艘白色渡轮从左向右行驶；东方明珠位于画面左侧三分之一，上海中心大厦为最高建筑并位于中右侧，金茂大厦与上海环球金融中心组成清晰的天际线；前景左下角保留少量外滩石栏杆；夏日18:50蓝调黄昏，薄云，城市灯光刚刚亮起。采用1980年代日本商业海报与City Pop封面插画的高饱和Pantone色彩：电光青、湖蓝、珊瑚红、明黄和深海军蓝，平涂色块与极细黑色轮廓，局部亮面高光，色彩像丝网印刷后的鲜艳油墨，画面干净、明快、时髦、带一点奢华都市生活感。不要复制任何具体艺术家的作品。保持建筑位置、镜头高度约1.6米、50mm视角和构图不变；不要增加棕榈树、海滩、游泳池、美国公路、人物特写、广告牌、可读文字、logo、水印、照片写实、3D渲染或拼贴。",
    "image": "images/02/chatgpt_1788061359913.png",
    "aspect": "landscape",
    "variant": null
  },
  {
    "id": "03",
    "sourceId": "03",
    "round": "round1",
    "roundLabel": "01 / 基准探索",
    "title": "粉彩丙烯黄昏",
    "prompt": "请创作一幅16:9宽幅城市绘画。固定场景：站在上海外滩中段的滨江步道，向东跨过黄浦江眺望陆家嘴；黄浦江占画面下方约三分之一，河面平静并有一艘白色渡轮从左向右行驶；东方明珠位于画面左侧三分之一，上海中心大厦为最高建筑并位于中右侧，金茂大厦与上海环球金融中心组成清晰的天际线；前景左下角保留少量外滩石栏杆；夏日18:50蓝调黄昏，薄云，城市灯光刚刚亮起。采用梦幻、轻盈的City Pop城市度假绘画：粉蓝、薰衣草紫、蜜桃橙、薄荷绿和暖米色的低对比粉彩配色，半透明丙烯薄涂，柔软空气感，边缘略微融化，天空和河面有宽阔平滑的色彩过渡，建筑仍保持简洁可识别，像一张被阳光晒过的1980年代旅行海报，浪漫但不过度甜腻。不要复制任何具体艺术家的作品。保持建筑位置、镜头高度约1.6米、50mm视角和构图不变；不要增加棕榈树、海滩、游泳池、美国公路、人物特写、广告牌、可读文字、logo、水印、照片写实、3D渲染或拼贴。",
    "image": "images/03/chatgpt_1788061449900.png",
    "aspect": "landscape",
    "variant": null
  },
  {
    "id": "04",
    "sourceId": "04",
    "round": "round1",
    "roundLabel": "01 / 基准探索",
    "title": "硬边几何极简",
    "prompt": "请创作一幅16:9宽幅城市绘画。固定场景：站在上海外滩中段的滨江步道，向东跨过黄浦江眺望陆家嘴；黄浦江占画面下方约三分之一，河面平静并有一艘白色渡轮从左向右行驶；东方明珠位于画面左侧三分之一，上海中心大厦为最高建筑并位于中右侧，金茂大厦与上海环球金融中心组成清晰的天际线；前景左下角保留少量外滩石栏杆；夏日18:50蓝调黄昏，薄云，城市灯光刚刚亮起。采用City Pop与1980年代现代主义海报结合的硬边几何绘画：把天空、江面、建筑和灯光概括为明确的矩形、圆弧、梯形和水平色带，使用深靛蓝、钴蓝、青绿、橘红、奶油黄，极少渐变，平整哑光丙烯表面，秩序感强，留白大胆，像精心设计的唱片封面而非照片。不要复制任何具体艺术家的作品。保持建筑位置、镜头高度约1.6米、50mm视角和构图不变；不要增加棕榈树、海滩、游泳池、美国公路、人物特写、广告牌、可读文字、logo、水印、照片写实、3D渲染或拼贴。",
    "image": "images/04/chatgpt_1788061509956.png",
    "aspect": "landscape",
    "variant": null
  },
  {
    "id": "05",
    "sourceId": "05",
    "round": "round1",
    "roundLabel": "01 / 基准探索",
    "title": "复古丝网印刷",
    "prompt": "请创作一幅16:9宽幅城市绘画。固定场景：站在上海外滩中段的滨江步道，向东跨过黄浦江眺望陆家嘴；黄浦江占画面下方约三分之一，河面平静并有一艘白色渡轮从左向右行驶；东方明珠位于画面左侧三分之一，上海中心大厦为最高建筑并位于中右侧，金茂大厦与上海环球金融中心组成清晰的天际线；前景左下角保留少量外滩石栏杆；夏日18:50蓝调黄昏，薄云，城市灯光刚刚亮起。采用复古City Pop唱片封面的手工丝网印刷绘画：3到5种专色套印，靛蓝、砖红、珊瑚橙、暖黄、米白，略微错版，边缘有油墨堆积和干燥颗粒，纸张有细小纤维与旧印刷压痕，建筑轮廓简化但准确，颜色有年代感，整体像一张收藏级1980年代城市艺术海报。不要复制任何具体艺术家的作品。保持建筑位置、镜头高度约1.6米、50mm视角和构图不变；不要增加棕榈树、海滩、游泳池、美国公路、人物特写、广告牌、可读文字、logo、水印、照片写实、3D渲染或拼贴。",
    "image": "images/05/chatgpt_1788061607363.png",
    "aspect": "landscape",
    "variant": null
  },
  {
    "id": "06",
    "sourceId": "06",
    "round": "round1",
    "roundLabel": "01 / 基准探索",
    "title": "彩色漫画叙事",
    "prompt": "请创作一幅16:9宽幅城市绘画。固定场景：站在上海外滩中段的滨江步道，向东跨过黄浦江眺望陆家嘴；黄浦江占画面下方约三分之一，河面平静并有一艘白色渡轮从左向右行驶；东方明珠位于画面左侧三分之一，上海中心大厦为最高建筑并位于中右侧，金茂大厦与上海环球金融中心组成清晰的天际线；前景左下角保留少量外滩石栏杆；夏日18:50蓝调黄昏，薄云，城市灯光刚刚亮起。采用成熟浪漫的1980年代彩色漫画与City Pop插画语言：纤细而有节奏的墨线，平涂水彩色块，局部透明叠色，建筑和江面被处理成带有情绪的舞台背景，加入极少量手绘速写线和柔和纸张颗粒，氛围是下班后独自散步时的都市浪漫，克制、优雅、微微感伤，不出现清晰人物脸部。不要复制任何具体艺术家的作品。保持建筑位置、镜头高度约1.6米、50mm视角和构图不变；不要增加棕榈树、海滩、游泳池、美国公路、人物特写、广告牌、可读文字、logo、水印、照片写实、3D渲染或拼贴。",
    "image": "images/06/chatgpt_1788061666534.png",
    "aspect": "landscape",
    "variant": null
  },
  {
    "id": "07",
    "sourceId": "07",
    "round": "round1",
    "roundLabel": "01 / 基准探索",
    "title": "深蓝霓虹漆彩",
    "prompt": "请创作一幅16:9宽幅城市绘画。固定场景：站在上海外滩中段的滨江步道，向东跨过黄浦江眺望陆家嘴；黄浦江占画面下方约三分之一，河面平静并有一艘白色渡轮从左向右行驶；东方明珠位于画面左侧三分之一，上海中心大厦为最高建筑并位于中右侧，金茂大厦与上海环球金融中心组成清晰的天际线；前景左下角保留少量外滩石栏杆；夏日18:50蓝调黄昏，薄云，城市灯光刚刚亮起。采用夜间City Pop绘画：深海军蓝和黑紫色为大面积底色，叠加品红、蓝绿、橙黄的霓虹反射，使用平滑丙烯与局部厚涂高光，灯光像湿润的漆面一样在江面拉出长条反射，建筑边缘清晰、光晕受控，带有1980年代模拟合成器封面般的夜色，但仍然是绘画而不是赛博朋克。不要复制任何具体艺术家的作品。保持建筑位置、镜头高度约1.6米、50mm视角和构图不变；不要增加棕榈树、海滩、游泳池、美国公路、人物特写、广告牌、可读文字、logo、水印、照片写实、3D渲染或拼贴。",
    "image": "images/07/chatgpt_1788061729933.png",
    "aspect": "landscape",
    "variant": null
  },
  {
    "id": "08",
    "sourceId": "08",
    "round": "round1",
    "roundLabel": "01 / 基准探索",
    "title": "蜡笔与胶片颗粒",
    "prompt": "请创作一幅16:9宽幅城市绘画。固定场景：站在上海外滩中段的滨江步道，向东跨过黄浦江眺望陆家嘴；黄浦江占画面下方约三分之一，河面平静并有一艘白色渡轮从左向右行驶；东方明珠位于画面左侧三分之一，上海中心大厦为最高建筑并位于中右侧，金茂大厦与上海环球金融中心组成清晰的天际线；前景左下角保留少量外滩石栏杆；夏日18:50蓝调黄昏，薄云，城市灯光刚刚亮起。采用温暖怀旧的City Pop手绘绘画：彩色铅笔、油画棒和马克笔叠加，保留可见的短笔触、交叉排线和纸张摩擦感，天空用粉蓝和桃粉轻轻铺开，建筑用海军蓝和暖灰概括，灯光用奶油黄点亮，加入很轻的模拟胶片颗粒和褪色边缘，像1980年代私人旅行画册中的一页，亲切、手工、带呼吸感。不要复制任何具体艺术家的作品。保持建筑位置、镜头高度约1.6米、50mm视角和构图不变；不要增加棕榈树、海滩、游泳池、美国公路、人物特写、广告牌、可读文字、logo、水印、照片写实、3D渲染或拼贴。",
    "image": "images/08/chatgpt_1788061829520.png",
    "aspect": "landscape",
    "variant": null
  },
  {
    "id": "09",
    "sourceId": "09",
    "round": "round1",
    "roundLabel": "01 / 基准探索",
    "title": "水粉透明叠染",
    "prompt": "请创作一幅16:9宽幅城市绘画。固定场景：站在上海外滩中段的滨江步道，向东跨过黄浦江眺望陆家嘴；黄浦江占画面下方约三分之一，河面平静并有一艘白色渡轮从左向右行驶；东方明珠位于画面左侧三分之一，上海中心大厦为最高建筑并位于中右侧，金茂大厦与上海环球金融中心组成清晰的天际线；前景左下角保留少量外滩石栏杆；夏日18:50蓝调黄昏，薄云，城市灯光刚刚亮起。采用具有空气感的City Pop水粉与透明水彩绘画：天空从钴蓝、薰衣草紫渐变到蜜桃橙，水面用稀释水彩形成自然流动的反光，建筑用不透明水粉保持清晰平面，局部边缘留出纸白，笔触轻薄、干湿并置、层层罩染，画面安静又有夏夜音乐般的节奏，保留手工绘画的水痕和颜料沉淀。不要复制任何具体艺术家的作品。保持建筑位置、镜头高度约1.6米、50mm视角和构图不变；不要增加棕榈树、海滩、游泳池、美国公路、人物特写、广告牌、可读文字、logo、水印、照片写实、3D渲染或拼贴。",
    "image": "images/09/chatgpt_1788061888250.png",
    "aspect": "landscape",
    "variant": null
  },
  {
    "id": "10",
    "sourceId": "10",
    "round": "round1",
    "roundLabel": "01 / 基准探索",
    "title": "当代上海复古合成",
    "prompt": "请创作一幅16:9宽幅城市绘画。固定场景：站在上海外滩中段的滨江步道，向东跨过黄浦江眺望陆家嘴；黄浦江占画面下方约三分之一，河面平静并有一艘白色渡轮从左向右行驶；东方明珠位于画面左侧三分之一，上海中心大厦为最高建筑并位于中右侧，金茂大厦与上海环球金融中心组成清晰的天际线；前景左下角保留少量外滩石栏杆；夏日18:50蓝调黄昏，薄云，城市灯光刚刚亮起。采用当代上海City Pop复古合成绘画：以1980年代城市度假插画的清爽空气感为基础，加入数字丙烯、丝网印刷色块和轻微模拟胶片颗粒，主色为深靛蓝、青绿色、珊瑚粉、香槟金，建筑线条干净，光线有柔和的镀铬反射，画面现代、克制、东方都市感明确，像一张今天重新设计的复古唱片封面；强调上海本地天际线，不要把城市变成东京、洛杉矶或抽象未来城市。不要复制任何具体艺术家的作品。保持建筑位置、镜头高度约1.6米、50mm视角和构图不变；不要增加棕榈树、海滩、游泳池、美国公路、人物特写、广告牌、可读文字、logo、水印、照片写实、3D渲染或拼贴。",
    "image": "images/10/chatgpt_1788061948500.png",
    "aspect": "landscape",
    "variant": null
  },
  {
    "id": "r2-01",
    "sourceId": "r2-01",
    "round": "round2",
    "roundLabel": "02 / 粗粝变量",
    "title": "椰子树与黄昏江岸",
    "prompt": "请创作一幅16:9横向City Pop绘画：夏日黄昏的上海外滩江岸，视线越过黄浦江望向陆家嘴，东方明珠、上海中心大厦和金茂大厦作为远处天际线，江面有一艘小白色渡轮。画面左侧前景加入一棵高大的椰子树剪影，椰叶被晚风吹向画面右侧，让上海的城市景观带有海岸度假海报的想象。采用粗糙而有颗粒的空气喷绘和丙烯刷法：天空用宽大的青蓝、紫粉和珊瑚色块快速铺开，边缘不必整齐，远处建筑只用概括性的深蓝轮廓和少量暖黄色点光表示，不要画清楚每一扇窗；河面用稀疏的横向粗笔触和断续反光表现。整体要像1980年代复古唱片插画，轻松、慵懒、略带理想化，不要精细建筑渲染，不要照片写实，不要赛博朋克，不要可读文字、logo或水印，不要把上海变成东京或洛杉矶。",
    "image": "images/r2-01/chatgpt_1788062479724.png",
    "aspect": "landscape",
    "variant": null
  },
  {
    "id": "r2-02",
    "sourceId": "r2-02",
    "round": "round2",
    "roundLabel": "02 / 粗粝变量",
    "title": "敞篷车看上海",
    "prompt": "请创作一幅16:9横向City Pop绘画：一辆奶油白与珊瑚红配色的1980年代敞篷车停在上海外滩道路边，画面从车后方低机位望向黄浦江和陆家嘴，东方明珠在左侧，上海中心大厦在远处中右侧，江面有一艘小白色渡轮，天边是宽阔的夏日晚霞和几朵白云。让敞篷车只占前景下方一小部分，不遮挡城市。采用粗颗粒的手工丙烯、马克笔和干刷笔触，轮廓略微颤动，色块不完全平整，车身高光用少量厚涂白色表示；远处灯火全部简化成稀疏的黄色和粉橙色小点，建筑细节被有意省略。气氛是慵懒、浪漫、带海岸公路想象的上海夏夜，绘画要有旧纸张和轻微胶片颗粒感，不要精细数字插画，不要摄影感，不要人物特写，不要可读文字、logo或水印。",
    "image": "images/r2-02/chatgpt_1788062567480.png",
    "aspect": "landscape",
    "variant": null
  },
  {
    "id": "r2-03",
    "sourceId": "r2-03",
    "round": "round2",
    "roundLabel": "02 / 粗粝变量",
    "title": "点状灯火夜景",
    "prompt": "请创作一幅16:9横向City Pop夜景绘画：上海外滩滨江向东望陆家嘴，东方明珠位于左侧，上海中心大厦和金茂大厦在中右侧，黄浦江占下方三分之一，一艘白色渡轮从左向右经过；前景右侧是一棵椰子树的黑色剪影，天空从深蓝过渡到品红和橙紫。重点表现一种粗糙、概括、非精细的绘画语言：城市建筑只保留大块深色形体，远处灯火用成百上千个大小不一的手绘点点来表示，江面反光也由断裂的彩色短点和短线组成，像旧丝网印刷与干刷叠加。色彩使用午夜蓝、靛青、品红、珊瑚橙、暖黄和少量青绿，霓虹要克制，不要变成赛博朋克。保留纸张纤维、油墨颗粒和轻微错版，不要清晰窗格、照片写实、3D、可读文字、logo或水印。",
    "image": "images/r2-03/chatgpt_1788062743376.png",
    "aspect": "landscape",
    "variant": null
  },
  {
    "id": "r2-04",
    "sourceId": "r2-04",
    "round": "round2",
    "roundLabel": "02 / 粗粝变量",
    "title": "白云、椰树与复古车",
    "prompt": "请创作一幅16:9横向City Pop绘画：上海外滩夏日傍晚，黄浦江对岸是可辨认的陆家嘴天际线，东方明珠在左侧，上海中心大厦高耸于中右侧，江面有一艘小白色渡轮；前景左下角是一棵弯向河面的椰子树，前景右下角露出一辆珊瑚红色老式敞篷车的车头，天空有几朵夸张、蓬松、被夕阳染成奶油白和桃粉色的白云。采用非常粗的丙烯和油画棒笔触，云朵、树叶和水面都能看到明显的手工涂抹、刮擦和断笔，建筑远景像几块被刷出来的深蓝色剪影，只用零散的暖色小点表现灯火。画面要有80年代城市度假唱片封面的松弛感和浪漫感，但仍保留上海地标。不要精细建筑，不要平滑AI渐变，不要照片写实，不要赛博朋克，不要可读文字、logo或水印。",
    "image": "images/r2-04/chatgpt_1788062832160.png",
    "aspect": "landscape",
    "variant": null
  },
  {
    "id": "r2-05",
    "sourceId": "r2-05",
    "round": "round2",
    "roundLabel": "02 / 粗粝变量",
    "title": "粗糙丝网印刷夜色",
    "prompt": "请创作一幅16:9横向City Pop绘画：从上海外滩看黄浦江和陆家嘴夜景，东方明珠位于左侧，上海中心大厦与金茂大厦位于中右侧，江面一艘白色渡轮缓慢经过；画面左边有一棵椰子树剪影，画面底部边缘隐约出现一辆老式敞篷车的车顶。使用三到五种专色进行粗糙丝网印刷式绘画：深海军蓝、青蓝、紫红、珊瑚橙、奶油黄；大面积平涂，但保留明显的干刷、漏墨、纸张纤维、版画颗粒和轻微套印错位。远处城市灯火不要画成细密窗格，只用疏密有变化的点点和小短线，江面用粗糙断续的横向反光。画面有复古唱片封面感、手工感和留白，不要精细商业插画，不要照片写实、3D、赛博朋克、可读文字、logo或水印。",
    "image": "images/r2-05/chatgpt_1788062891418.png",
    "aspect": "landscape",
    "variant": null
  },
  {
    "id": "r2-06-1",
    "sourceId": "r2-06",
    "round": "round2",
    "roundLabel": "02 / 粗粝变量",
    "title": "最小化抽象城市",
    "prompt": "请创作一幅16:9横向City Pop绘画：上海黄浦江边的夏日蓝调时刻，远处是简化但仍可辨认的陆家嘴天际线，东方明珠在左侧，上海中心大厦在中右侧，江面有一艘极简白色渡轮，前景只保留一棵椰子树的局部黑色剪影和一小段外滩石栏杆，天空有两三朵宽大的白云。把城市远景和江面抽象成少量宽阔的粗笔触、色带和不规则色块，建筑窗灯只使用极少量手绘黄色点点；不要描绘每栋楼的结构，不要细密线稿，不要锐利边缘。主色为钴蓝、深靛蓝、珊瑚粉、橘黄、奶油白和一点薄荷青，颜料要有干燥、粗粝、颗粒化、带刮擦的质感，像一张被反复印刷过的1980年代城市艺术唱片封面。整体安静、开阔、略带梦境感，不要照片写实、平滑3D、赛博朋克、可读文字、logo或水印。",
    "image": "images/r2-06/chatgpt_1788062997725_1.png",
    "aspect": "landscape",
    "variant": 1
  },
  {
    "id": "r2-06-2",
    "sourceId": "r2-06",
    "round": "round2",
    "roundLabel": "02 / 粗粝变量",
    "title": "最小化抽象城市 · 另一输出",
    "prompt": "请创作一幅16:9横向City Pop绘画：上海黄浦江边的夏日蓝调时刻，远处是简化但仍可辨认的陆家嘴天际线，东方明珠在左侧，上海中心大厦在中右侧，江面有一艘极简白色渡轮，前景只保留一棵椰子树的局部黑色剪影和一小段外滩石栏杆，天空有两三朵宽大的白云。把城市远景和江面抽象成少量宽阔的粗笔触、色带和不规则色块，建筑窗灯只使用极少量手绘黄色点点；不要描绘每栋楼的结构，不要细密线稿，不要锐利边缘。主色为钴蓝、深靛蓝、珊瑚粉、橘黄、奶油白和一点薄荷青，颜料要有干燥、粗粝、颗粒化、带刮擦的质感，像一张被反复印刷过的1980年代城市艺术唱片封面。整体安静、开阔、略带梦境感，不要照片写实、平滑3D、赛博朋克、可读文字、logo或水印。",
    "image": "images/r2-06/chatgpt_1788062997725_2.png",
    "aspect": "landscape",
    "variant": 2
  },
  {
    "id": "r3-01",
    "sourceId": "r3-01",
    "round": "round3",
    "roundLabel": "03 / 规律吸收",
    "title": "上海灯火与三棵椰子树",
    "prompt": "采用以下视觉规律：大面积紫罗兰到粉紫色的平静天空、热带树木黑色剪影、远处建筑压缩成横向色带、城市灯火用密集点点和短横线表示、低细节、粗颗粒丝网印刷感；只吸收这些视觉规律，不复制任何具体作品或原图构图。创作一幅4:5竖幅上海City Pop绘画：画面上方三分之二是大面积紫罗兰到粉紫色的平静天空，画面中央是三棵高低错落的椰子树黑色剪影，椰叶细长、略微被风吹向一侧；下方是横向压缩的上海陆家嘴天际线，东方明珠在左侧，上海中心大厦和金茂大厦在右侧，黄浦江位于最下方。把远处建筑简化为深靛蓝色的横向色带和少量几何楼体，所有窗灯不要画成细密窗格，而是用密集但大小不一的奶油黄色、淡紫色和白色点点、短横线和小色块来表示，像远处城市被抽象成闪烁的颗粒。采用粗糙的丝网印刷与干刷混合笔触，明显的纸张纤维、半色调颗粒、轻微套印错位、边缘不整齐；使用深靛蓝、紫蓝、薰衣草紫、粉红、奶油黄五到六种主色，大面积平涂，不要平滑高清渐变。画面安静、理想化、带热带都市度假感。不要照片写实、不要精细建筑窗格、不要3D、不要赛博朋克、不要可读文字、logo或水印。",
    "image": "images/r3-01/chatgpt_1788065936213.png",
    "aspect": "portrait",
    "variant": null
  },
  {
    "id": "r3-02",
    "sourceId": "r3-02",
    "round": "round3",
    "roundLabel": "03 / 规律吸收",
    "title": "上海天际线旁的度假泳池",
    "prompt": "采用以下视觉规律：热带度假构图、泳池透视、向两侧倾斜的椰子树、纯色天空、植物点描、硬边色块和粗糙手工印刷质感；只提取这些视觉规律，不复制任何具体作品。创作一幅4:5竖幅上海City Pop绘画：前景是一个极简的矩形屋顶无边泳池，白色几何池畔从画面底部向远处收缩，浅蓝池水中用稀疏的白色小点和短线表现波光；泳池后方是深绿色的低矮灌木和三到四棵向两侧倾斜的椰子树，远处越过黄浦江看见上海陆家嘴天际线，东方明珠在左侧，上海中心大厦在右侧，建筑只作为简化的蓝色远景，不要精细描绘。天空占画面上方一半以上，使用明亮的青蓝色，保留一两朵扁平、奶油白的云。植物叶片用粗线、断笔和亮绿色短划表现，灌木用白色、浅绿和深绿的点描表示；池畔、建筑和地面使用硬朗的深蓝轮廓与大色块。整体采用粗糙丙烯、马克笔和丝网印刷混合笔触，带纸张颗粒、颜料干裂和轻微错版，颜色为青蓝、深绿、奶油白、钴蓝、珊瑚粉少量点缀。画面开阔、安静、奢华但克制，像1980年代城市度假唱片封面。不要人物、不要汽车、不要照片写实、不要过度细节、不要赛博朋克、不要可读文字、logo或水印。",
    "image": "images/r3-02/chatgpt_1788066014099.png",
    "aspect": "portrait",
    "variant": null
  },
  {
    "id": "r3-03",
    "sourceId": "r3-03",
    "round": "round3",
    "roundLabel": "03 / 规律吸收",
    "title": "点光上海夜海岸",
    "prompt": "采用以下视觉规律：大面积天空、简化横向地平线、椰子树剪影、硬边色块、点状光线和粗颗粒模拟印刷质感；只吸收这些规律，不复制任何具体作品。创作一幅4:5竖幅上海City Pop夜景绘画：画面上方是深蓝、紫罗兰和珊瑚粉组成的宽阔夜空，左侧前景有一棵大椰子树剪影，树叶形成强烈的黑色图形；画面中部将上海陆家嘴压缩成一条低矮而清晰的横向城市带，东方明珠在左侧，上海中心大厦在右侧，黄浦江位于下方。远处的建筑不要画窗格和线稿，而要用大量奶油黄、浅粉、橙色和白色的点点、短横线、断裂小块来表现城市灯火，点的密度在天际线中心更高，边缘更稀疏；江面用粗糙的水平短笔触和点状反光回应灯火。采用有限色版画、干刷和粗颗粒丙烯的混合方式，保留明显纸张纤维、油墨颗粒、半色调网点和轻微套印错位，轮廓硬朗但不精细，城市远景要有抽象概括感。主色为午夜蓝、靛蓝、紫红、珊瑚橙和奶油黄，整体安静、成熟、略带海岸夜风，不要变成赛博朋克。不要照片写实、不要精细建筑、不要平滑AI渐变、不要人物特写、不要可读文字、logo或水印。",
    "image": "images/r3-03/chatgpt_1788066132128.png",
    "aspect": "portrait",
    "variant": null
  }
,
{
    "id": "r4-01",
    "sourceId": "r4-01",
    "round": "round4",
    "roundLabel": "04 / 局部取景",
    "title": "石库门屋顶的椰影",
    "prompt": "请创作一幅4:5竖幅上海City Pop绘画，取景不是外滩全景，而是石库门弄堂的屋顶局部：前景是低矮的深靛蓝色屋顶女儿墙、简单晾衣杆和一把奶油色折叠躺椅，画面左侧伸出一棵被晚风吹斜的椰子树黑色剪影；远处只从屋顶之间露出东方明珠一小段球体和上海中心大厦窄窄的轮廓，城市被压缩成一条低矮的深蓝色横向色带。天空占画面上方三分之二，从钴蓝过渡到紫罗兰和珊瑚粉，灯火不要画成窗格，只用稀疏、大小不一的奶油黄色点点和短横线表示。采用粗糙丝网印刷、干刷和丙烯薄涂混合笔触，边缘略微不齐，保留纸张纤维、半色调网点、油墨颗粒和轻微套印错位；主色为午夜蓝、紫蓝、粉紫、珊瑚橙、奶油黄，画面安静、开阔、像一张复古城市度假唱片封面。不要完整外滩全景、不要精细建筑、不要照片写实、不要平滑AI渐变、不要人物、不要可读文字、logo、水印、3D或赛博朋克。",
    "image": "images/r4-01/chatgpt_1788077996581.png",
    "aspect": "portrait",
    "variant": null
  },
  {
    "id": "r4-02",
    "sourceId": "r4-02",
    "round": "round4",
    "roundLabel": "04 / 局部取景",
    "title": "苏州河桥下的车尾",
    "prompt": "请创作一幅4:5竖幅上海City Pop绘画，取景为苏州河一座老桥下的局部：画面下方是狭窄的青蓝色河面和几条粗糙的水平反光，前景右下角只露出一辆奶油白与珊瑚红复古敞篷车的后视镜、车尾和一点铬亮高光，左侧是一只种在水泥花池里的高大棕榈树剪影；桥拱和栏杆形成大块深靛蓝几何形，远处只露出东方明珠的细小轮廓和两三栋被压扁的上海建筑。天空从桥拱之外露出大片紫蓝、桃粉和橙紫，远处灯光全部简化为稀疏的黄色、粉橙色点点。采用粗颗粒丙烯、马克笔、干刷和旧丝网印刷质感，轮廓略微颤动，色块不完全平整，河面用断裂短线和点状反光表达；保留纸张纤维、漏墨、干燥颗粒和轻微错版。整体慵懒、带海岸公路想象但仍然明确是上海局部。不要外滩全景、不要精细窗格、不要照片写实、不要平滑数字插画、不要人物、不要可读文字、logo、水印、3D或赛博朋克。",
    "image": "images/r4-02/chatgpt_1788078124170.png",
    "aspect": "portrait",
    "variant": null
  },
  {
    "id": "r4-03",
    "sourceId": "r4-03",
    "round": "round4",
    "roundLabel": "04 / 局部取景",
    "title": "陆家嘴楼顶泳池切片",
    "prompt": "请创作一幅4:5竖幅上海City Pop绘画，取景为陆家嘴一座高层建筑屋顶的极简泳池局部：浅蓝色矩形池水从画面底部向远处收缩，池水只用疏落的奶油白点点和短线表现波光，白色池畔形成硬朗的几何边；泳池尽头被两三丛深绿色热带植物挡住，只露出上海中心大厦的上半段、金茂大厦的一角和东方明珠一颗小小的球体，不要完整天际线。天空占画面上方三分之二，使用明亮青蓝、紫蓝和少量珊瑚粉，保留一朵扁平的奶油白云。植物叶片用粗线、断笔和亮绿色短划画出，建筑只用深蓝色平涂形体，远处灯光用极少量暖黄点点。采用粗糙丙烯、有限色丝网印刷和旧纸颗粒，明显保留干刷、颜料刮擦、半色调网点和轻微套印错位；画面安静、奢华但克制，像一张被晒过的1980年代城市度假唱片封面。不要外滩全景、不要人物、不要汽车、不要精细建筑、不要照片写实、不要平滑AI渐变、不要可读文字、logo、水印、3D或赛博朋克。",
    "image": "images/r4-03/chatgpt_1788078245416.png",
    "aspect": "portrait",
    "variant": null
  },
  {
    "id": "r4-04",
    "sourceId": "r4-04",
    "round": "round4",
    "roundLabel": "04 / 局部取景",
    "title": "梧桐街角与珊瑚车头",
    "prompt": "请创作一幅4:5竖幅上海City Pop绘画，取景为武康路或复兴西路一处安静的街角局部：画面左侧是一棵巨大的上海梧桐树黑色剪影，树冠切进大面积的蓝紫天空；右下角只露出一辆珊瑚红色1980年代敞篷车的车头、后视镜和奶油白高光，背景是一幢浅米色老公寓的几何立面和一小段深蓝色街道，不要画完整街景；远处灯火被压缩成零散的暖黄色点点，上海感来自梧桐、老公寓和克制的城市尺度，不添加外滩全景。天空使用钴蓝、薰衣草紫、粉紫和一点夕阳橙，树叶和建筑边缘用粗糙干刷与断续马克笔线表现，色块大而平，轮廓硬朗但不精细。加入旧纸张纤维、胶片颗粒、油墨漏印、半色调网点和轻微套印错位，像手工制作的复古城市唱片封面。气氛慵懒、成熟、微微浪漫。不要人物、不要可读店招、不要logo、水印、不要精细窗格、不要照片写实、不要平滑数字插画、不要3D或赛博朋克。",
    "image": "images/r4-04/chatgpt_1788078405065.png",
    "aspect": "portrait",
    "variant": null
  },
  {
    "id": "r4-05",
    "sourceId": "r4-05",
    "round": "round4",
    "roundLabel": "04 / 局部取景",
    "title": "渡轮甲板看一颗明珠",
    "prompt": "请创作一幅4:5竖幅上海City Pop夜景绘画，取景只截取黄浦江渡轮甲板的一角：画面下方是深蓝色水面和一小段奶油白渡轮栏杆，栏杆上的一块珊瑚红救生圈只作为简单色块；画面左侧近处是一棵河岸棕榈树的黑色剪影，远处只让东方明珠的一颗球体和上海中心大厦顶部从低矮城市带后方露出，地平线不要展开成完整天际线。天空占画面上方四分之三，从午夜蓝到紫红和珊瑚橙形成大面积平涂色带，城市灯火用密集但大小不一的奶油黄、浅粉和白色点点、短横线和断裂小块表示，江面反光回应这些点光。采用粗糙有限色版画、干刷和颗粒丙烯混合笔触，保留纸张纤维、油墨颗粒、半色调网点、漏墨和轻微错版，轮廓硬朗但有手工不整齐感。画面安静、带夜风和海岸度假想象，但仍明确是上海。不要外滩全景、不要精细窗格、不要人物、不要照片写实、不要平滑AI渐变、不要可读文字、logo、水印、3D或赛博朋克。",
    "image": "images/r4-05/chatgpt_1788078530447.png",
    "aspect": "portrait",
    "variant": null
  },
  {
    "id": "r4-06",
    "sourceId": "r4-06",
    "round": "round4",
    "roundLabel": "04 / 局部取景",
    "title": "前滩长椅与远处高楼",
    "prompt": "请创作一幅4:5竖幅上海City Pop日落绘画，取景为前滩滨江公园一处局部：前景是一张深蓝色混凝土长椅和一块奶油白的几何地面，画面右侧伸出一棵低矮棕榈树的叶片剪影，长椅后方只保留一条青蓝色江面和一小块被压缩的上海城市带；上海中心大厦与东方明珠只作为远处两个清晰但极简的形体，不要完整全景。天空占画面上方三分之二，使用明亮青蓝、薰衣草紫、桃粉和暖橙色的大色带，保留两朵扁平、夸张、奶油白的云。江面和远处灯火用稀疏的点点、短横线和粗糙断笔表现，植物用深绿、黑蓝和亮绿色短划点描。采用有限色丝网印刷、粗丙烯和旧纸张质感，边缘不必整齐，加入颜料刮擦、干刷、半色调颗粒、纸张纤维和轻微套印错位。画面开阔、安静、带城市度假感。不要外滩全景、不要人物、不要汽车、不要精细建筑、不要照片写实、不要平滑AI渐变、不要可读文字、logo、水印、3D或赛博朋克。",
    "image": "images/r4-06/chatgpt_1788078700471.png",
    "aspect": "portrait",
    "variant": null
  },
{
  "id": "bj-01",
  "sourceId": "bj-01",
  "round": "round5",
  "roundLabel": "05 / 北京局部",
  "title": "故宫红墙的一角",
  "prompt": "请创作一幅4:5竖幅北京City Pop绘画，取景不是天安门或故宫全景，而是故宫红墙的一处局部：前景为深朱红色墙体、奶油白石台和一小段琉璃瓦屋檐，左侧伸出一棵修剪感很弱的古松黑色剪影；墙体开口之外只露出一座角楼屋顶和极低的蓝色城市线，建筑不要铺满画面。天空占上方三分之二，从钴蓝、紫罗兰过渡到珊瑚粉，远处灯火只用稀疏的奶油黄色点点和短横线表示。采用粗糙有限色丝网印刷、干刷和颗粒丙烯混合笔触，红墙色块边缘略不齐，保留纸张纤维、半色调网点、油墨漏印和轻微套印错位；主色为朱红、深靛蓝、紫蓝、珊瑚橙、奶油黄。画面安静、理想化、像一张北京城市度假唱片封面。不要完整故宫或城市全景、不要人物、不要旗帜、不要可读文字、logo、水印、照片写实、平滑AI渐变、3D或赛博朋克。",
  "image": "images/bj-01/chatgpt_1788080561323.png",
  "aspect": "portrait",
  "variant": null,
  "city": "北京"
},
{
  "id": "bj-02",
  "sourceId": "bj-02",
  "round": "round5",
  "roundLabel": "05 / 北京局部",
  "title": "什刹海柳影与点光",
  "prompt": "请创作一幅4:5竖幅北京City Pop绘画，取景为什刹海一段狭窄的湖岸局部：画面下方是青蓝色水面和几条粗糙的水平反光，前景右侧露出一辆奶油白复古自行车的车把和后视镜，左侧垂下几枝北京垂柳黑色剪影；远处只露出鼓楼屋顶的一小段和低矮胡同屋脊，不要展开完整湖面或城市天际线。天空占画面上方三分之二，使用青蓝、薰衣草紫、桃粉和暖橙色大色带，湖面灯光简化为大小不一的奶油黄、粉橙色点点和断裂短线。采用粗颗粒丙烯、干刷、有限色丝网印刷和旧纸纹理，柳叶、水面和屋顶都保留明显的断笔、刮擦、半色调颗粒和轻微错版。整体慵懒、安静、带夏日晚风，不要什刹海全景、不要人物、不要精细建筑窗格、不要照片写实、不要平滑数字插画、不要可读文字、logo、水印、3D或赛博朋克。",
  "image": "images/bj-02/chatgpt_1788080683447.png",
  "aspect": "portrait",
  "variant": null,
  "city": "北京"
},
{
  "id": "bj-03",
  "sourceId": "bj-03",
  "round": "round5",
  "roundLabel": "05 / 北京局部",
  "title": "鼓楼街角的珊瑚车",
  "prompt": "请创作一幅4:5竖幅北京City Pop绘画，取景为鼓楼附近一条胡同的街角局部：画面右下角只露出一辆珊瑚红色1980年代敞篷车的车头、圆形后视镜和奶油白高光，左侧是一棵北京国槐的粗大黑色树干与枝叶剪影；背景只保留鼓楼灰色屋顶和一段朱红色墙面，被压缩成几个大块几何形体，不能画成完整街景。天空占画面上方一半以上，从深蓝、紫红到橙粉色平涂过渡，远处的灯火只用零散小点表示。采用粗糙丝网印刷、干刷和马克笔叠加的手工笔触，车身高光略厚涂，树皮、墙面和天空保留纸张纤维、漏墨、半色调网点与轻微套印错位。画面慵懒、成熟、略带复古公路想象，但北京识别度来自鼓楼、胡同、国槐和灰瓦。不要完整鼓楼全景、不要店招文字、不要人物、不要照片写实、不要平滑渐变、不要3D或赛博朋克。",
  "image": "images/bj-03/chatgpt_1788080839881.png",
  "aspect": "portrait",
  "variant": null,
  "city": "北京"
},
{
  "id": "bj-04",
  "sourceId": "bj-04",
  "round": "round5",
  "roundLabel": "05 / 北京局部",
  "title": "颐和园长廊看湖光",
  "prompt": "请创作一幅4:5竖幅北京City Pop绘画，取景为颐和园长廊的一段局部：前景左侧是朱红色长廊柱子和一小块褪色彩绘梁，右侧留出开阔的青蓝色昆明湖水面，岸边垂柳和荷叶只作为深绿剪影；远处只露出一角佛香阁或西山轮廓，不要完整园林全景。天空占画面上方三分之二，使用明亮青蓝、紫蓝、珊瑚粉和奶油白，保留一朵扁平的大白云；湖面用疏落的奶油黄、浅粉色点点和粗糙水平短线表现光。采用粗丙烯、有限色丝网印刷、干刷和旧纸颗粒，柱子、云朵、柳叶和水面都能看到不整齐边缘、刮擦和半色调网点。画面开阔、清凉、带城市度假感，但仍然是北京的皇家园林局部。不要完整颐和园全景、不要人物、不要精细古建、不要照片写实、不要平滑AI渐变、不要可读文字、logo、水印、3D或赛博朋克。",
  "image": "images/bj-04/chatgpt_1788080990145.png",
  "aspect": "portrait",
  "variant": null,
  "city": "北京"
},
{
  "id": "bj-05",
  "sourceId": "bj-05",
  "round": "round5",
  "roundLabel": "05 / 北京局部",
  "title": "天坛祈年殿的蓝调",
  "prompt": "请创作一幅4:5竖幅北京City Pop蓝调时刻绘画，取景只截取天坛祈年殿的上半段：圆形三重檐屋顶从画面右侧切入，深蓝色屋檐和朱红色柱体被概括成硬朗的大色块，前景左侧有一株古柏的黑色剪影，建筑下方不要出现完整广场。天空占画面上方四分之三，从钴蓝到薰衣草紫和珊瑚粉平涂，屋檐边缘留出大量空白；远处灯光只用极少量暖黄色点点，不画细密窗格。采用粗糙有限色版画、干刷和颗粒丙烯，屋顶线条略微颤动，朱红墙面有干燥、漏墨、纸张纤维和轻微套印错位的质感。主色为深靛蓝、紫蓝、朱红、珊瑚橙和奶油黄，整体安静、庄重、理想化。不要天坛全景、不要游客、不要旗帜、不要照片写实、不要精细瓦片、不要平滑数字渐变、不要可读文字、logo、水印、3D或赛博朋克。",
  "image": "images/bj-05/chatgpt_1788081272062.png",
  "aspect": "portrait",
  "variant": null,
  "city": "北京"
},
{
  "id": "bj-06",
  "sourceId": "bj-06",
  "round": "round5",
  "roundLabel": "05 / 北京局部",
  "title": "国贸屋顶泳池切片",
  "prompt": "请创作一幅4:5竖幅北京City Pop绘画，取景为北京国贸高层屋顶的一处极简泳池局部：浅蓝色矩形池水从画面底部向远处收缩，奶油白池畔形成硬朗几何边，前景只露出一把珊瑚红折叠躺椅和一小盆深绿色植物；泳池后方只露出中国尊上半段和一座玻璃高楼的局部，不要完整CBD天际线。天空占画面上方三分之二，使用明亮青蓝、紫蓝、桃粉和奶油白，保留一朵扁平白云；池水用疏落的白色点点和短线表现波光，远处建筑只用深蓝色平涂形体和少量暖黄点光。采用粗糙丙烯、有限色丝网印刷、干刷和旧纸颗粒，保留颜料刮擦、半色调网点、纸张纤维和轻微错版。画面奢华但克制，把北京高楼变成热带度假唱片里的远景记号。不要完整国贸全景、不要人物、不要广告牌、不要可读文字、不要照片写实、不要平滑AI渐变、不要3D或赛博朋克。",
  "image": "images/bj-06/chatgpt_1788081928726.png",
  "aspect": "portrait",
  "variant": null,
  "city": "北京"
},
{
  "id": "bj-07",
  "sourceId": "bj-07",
  "round": "round5",
  "roundLabel": "05 / 北京局部",
  "title": "鸟巢曲线与水面",
  "prompt": "请创作一幅4:5竖幅北京City Pop绘画，取景为奥林匹克公园一处局部：画面右侧只出现鸟巢外立面的一段银灰色交错曲线，前景是深蓝色水池边缘和几丛低矮草叶，左下角保留一块珊瑚橙色的混凝土座面；不要画完整鸟巢和完整公园。天空占画面上方三分之二，使用钴蓝、紫红、珊瑚粉和暖橙色的大色块，水面用奶油白、浅粉和青绿色的点点与断续短线反光。采用粗糙丝网印刷、干刷和颗粒丙烯，银灰结构不要精细工程线稿，而是概括成几块硬边图形，保留纸张纤维、油墨颗粒、漏印和轻微套版偏移。画面有北京现代城市的识别度，也有1980年代城市度假封面的松弛感。不要奥林匹克公园全景、不要运动员、不要广告、不要可读文字、不要照片写实、不要平滑3D、不要赛博朋克。",
  "image": "images/bj-07/chatgpt_1788082257999.png",
  "aspect": "portrait",
  "variant": null,
  "city": "北京"
},
{
  "id": "bj-08",
  "sourceId": "bj-08",
  "round": "round5",
  "roundLabel": "05 / 北京局部",
  "title": "景山松枝下的金色屋顶",
  "prompt": "请创作一幅4:5竖幅北京City Pop绘画，取景为景山的一处山坡局部：前景左侧是一根深黑色古松枝干和几簇松针，画面下方只有一小段粗糙石台；松枝之间远远露出故宫一条金色屋顶线和一座角楼的局部，不要俯拍完整故宫。天空占画面上方四分之三，从青蓝、紫罗兰到柔和珊瑚橙平涂，空中只留一根细细的风筝线和一枚很小的几何风筝，不出现人物。远处建筑和灯火简化为深蓝色横向色带、奶油黄色点点和短横线。采用粗颗粒丙烯、干刷、有限色丝网印刷和旧纸纹理，松针、石台和屋顶边缘不必整齐，保留刮擦、半色调网点、漏墨和轻微套印错位。画面安静、带风、略有梦境感。不要故宫全景、不要人物脸部、不要旅游纪念品文字、不要照片写实、不要平滑AI渐变、不要3D或赛博朋克。",
  "image": "images/bj-08/chatgpt_1788082466741.png",
  "aspect": "portrait",
  "variant": null,
  "city": "北京"
},
{
  "id": "bj-09",
  "sourceId": "bj-09",
  "round": "round5",
  "roundLabel": "05 / 北京局部",
  "title": "银杏胡同月色",
  "prompt": "请创作一幅4:5竖幅北京City Pop夜景绘画，取景为一条安静胡同的院墙和屋檐局部：画面左侧是一棵巨大的银杏树黑色剪影，右侧是灰瓦屋檐、朱红色门框和一小块深蓝色院墙，远处窗灯不要画成细密窗格，只用疏密变化的奶油黄小点和短横线表示；画面上方留出大面积午夜蓝与紫红夜空，挂一轮极简的奶油白月亮。地面只保留一小段深靛蓝砖路和几片金黄色落叶，避免完整街道透视。采用粗糙有限色版画、干刷、颗粒丙烯和旧纸纤维，树叶、墙面和月光都保留漏墨、半色调网点、干裂颜料和轻微错版，轮廓硬朗但不精细。主色为午夜蓝、靛青、紫红、朱红和奶油黄，气氛安静、成熟、带北京夜风。不要胡同全景、不要人物、不要店招、不要可读文字、logo、水印、照片写实、平滑数字渐变、3D或赛博朋克。",
  "image": "images/bj-09/chatgpt_1788082758077.png",
  "aspect": "portrait",
  "variant": null,
  "city": "北京"
},
{
  "id": "bj-10",
  "sourceId": "bj-10",
  "round": "round5",
  "roundLabel": "05 / 北京局部",
  "title": "居庸关城墙的斜线",
  "prompt": "请创作一幅4:5竖幅北京City Pop绘画，取景为居庸关长城的一段局部：前景是一条从左下向右上斜切的深靛蓝色城墙和一座烽火台的局部，墙垛不要逐块精细描绘；右侧伸出一棵山坡油松的黑色剪影，远处山脊被压缩成紫蓝色横向色带。天空占画面上方三分之二，使用钴蓝、紫罗兰、珊瑚粉和橙金色的宽阔平涂色带，保留两朵扁平奶油白云；山谷和墙脚的灯光只用稀疏奶油黄色点点和短线表示。采用粗糙丝网印刷、干刷、颗粒丙烯和旧纸质感，石墙边缘略不齐，保留纸张纤维、油墨堆积、半色调网点、刮擦和轻微套印错位。画面开阔、安静、带北京北方山风和复古城市旅行唱片感。不要完整长城全景、不要游客、不要旗帜、不要照片写实、不要精细砖石、不要平滑AI渐变、不要可读文字、logo、水印、3D或赛博朋克。",
  "image": "images/bj-10/chatgpt_1788083029057.png",
  "aspect": "portrait",
  "variant": null,
  "city": "北京"
},
{
  "id": "r6-01",
  "sourceId": "r6-01",
  "round": "round6",
  "roundLabel": "06 / 参考规律",
  "title": "梧桐树冠下的武康路",
  "prompt": "Use case: stylized-concept. Asset type: vertical web gallery artwork. Input images: Image 1, Image 2, Image 3 are reference images for brushwork, palette, composition and print texture only; do not copy their exact scenes or layouts. Primary request: 原创一幅上海武康路街角的4:5竖幅绘画，从一棵巨大梧桐树下向上看，左侧和上方被深绿树冠包住，右下只露出奶油色老公寓的一角、阳台和一小段安静街道，远处只保留一根很小的城市塔尖作为上海暗示，不画外滩全景。 Style/medium: rough hand-painted gouache and acrylic editorial illustration fused with limited-color screen print; broad flat blocks, visibly coarse dry-brush, broken edges, scraped pigment, irregular halftone dots, paper fibers, slight ink misregistration; distant windows and lights simplified into sparse hand-placed dots and short dashes. Composition/framing: 4:5 portrait, giant foreground tree as an edge frame, 60% open cobalt-blue sky, simple layered silhouettes, strong diagonal branch. Lighting/mood: clear late-summer afternoon turning toward violet evening, calm, breezy, idealized city vacation mood. Color palette: cobalt blue, cerulean, violet, leaf green, deep indigo, citrus yellow, a small coral accent. Constraints: Shanghai-specific but original, rough and visibly handmade, no exact reference recreation. Avoid: photorealism, glossy digital rendering, smooth AI gradients, hyper-detailed leaves or windows, full skyline panorama, readable signs, logos, watermark, 3D, cyberpunk, collage, or any artist imitation.",
  "image": "images/r6-01/citypop-shanghai-01.png",
  "aspect": "portrait",
  "variant": null,
  "city": "上海"
},
{
  "id": "r6-02",
  "sourceId": "r6-02",
  "round": "round6",
  "roundLabel": "06 / 参考规律",
  "title": "苏州河桥拱里的晚风",
  "prompt": "Use case: stylized-concept. Asset type: vertical web gallery artwork. Input images: Image 1, Image 2, Image 3 are reference images for brushwork, palette, composition and print texture only; do not copy their exact scenes or layouts. Primary request: 原创一幅上海苏州河的4:5竖幅局部绘画，前景用深蓝色老桥的一段巨大桥拱从左侧切入，桥拱内部框住一片紫粉色水面和一小段对岸树影，右下露出一辆停靠的复古自行车或小踏板车，远处仅有一座低矮工业建筑的轮廓与零散灯点，不画完整河岸。 Style/medium: rough hand-painted gouache and acrylic editorial illustration fused with limited-color screen print; broad flat blocks, coarse dry-brush, broken edges, scraped pigment, irregular halftone dots, paper fibers, slight ink misregistration; reflections are short broken dashes and dots rather than smooth realism. Composition/framing: 4:5 portrait, bridge arch as a bold dark frame, large open turquoise-to-violet sky, low horizon, one simple diagonal waterline. Lighting/mood: blue hour after a hot day, quiet river breeze, a little nostalgic. Color palette: deep navy, cobalt, turquoise, violet, coral orange, warm cream, restrained yellow-green. Constraints: the bridge and river must feel like Shanghai, but the scene is a local fragment, not a panorama. Avoid: photorealism, precise masonry, smooth gradients, dense windows, readable storefront text, logos, watermark, 3D, cyberpunk, collage, or exact reference copying.",
  "image": "images/r6-02/citypop-shanghai-02.png",
  "aspect": "portrait",
  "variant": null,
  "city": "上海"
},
{
  "id": "r6-03",
  "sourceId": "r6-03",
  "round": "round6",
  "roundLabel": "06 / 参考规律",
  "title": "石库门天井的热带借景",
  "prompt": "Use case: stylized-concept. Asset type: vertical web gallery artwork. Input images: Image 1, Image 2, Image 3 are reference images for brushwork, palette, composition and print texture only; do not copy their exact scenes or layouts. Primary request: 原创一幅上海石库门里弄天井的4:5竖幅绘画，画面下方是深红砖墙与拱门的局部，左上伸入一片夸张的棕榈叶和一根晾衣杆，中央留出明亮青蓝天空，拱门后只露出一小块现代高楼和几盏被压缩成点点的灯，不画完整里弄。 Style/medium: rough hand-painted gouache and acrylic editorial illustration fused with limited-color screen print; broad flat color blocks, very coarse dry-brush, uneven hand-painted edges, scraped pigment, irregular halftone dots, paper fibers, slight misregistration; leaves and hanging cloth use simplified mark clusters. Composition/framing: 4:5 portrait, red architecture anchors the bottom, tropical leaf frames the top corner, large sky negative space, one clear vertical axis. Lighting/mood: warm sunset afterglow, intimate but airy, nostalgic urban resort fantasy. Color palette: brick coral-red, deep indigo, turquoise blue, leaf green, magenta violet, cream yellow. Constraints: recognizable Shanghai lane-house geometry without fine architectural rendering. Avoid: photorealism, perfect linework, smooth digital gradients, too many objects, people, readable characters, signs, logos, watermark, 3D, cyberpunk, collage, or exact reference recreation.",
  "image": "images/r6-03/citypop-shanghai-03.png",
  "aspect": "portrait",
  "variant": null,
  "city": "上海"
},
{
  "id": "r6-04",
  "sourceId": "r6-04",
  "round": "round6",
  "roundLabel": "06 / 参考规律",
  "title": "渡轮甲板与黄浦江点光",
  "prompt": "Use case: stylized-concept. Asset type: vertical web gallery artwork. Input images: Image 1, Image 2, Image 3 are reference images for brushwork, palette, composition and print texture only; do not copy their exact scenes or layouts. Primary request: 原创一幅上海黄浦江渡轮甲板的4:5竖幅绘画，前景下方是一段深蓝栏杆和一只珊瑚橙救生圈，视线越过平静江面望向被压缩成深色横向色带的上海岸线，东方明珠只作为很小的亮点或细线出现，天空占画面三分之二，可有一朵扁平奶油白云。 Style/medium: rough hand-painted gouache and acrylic editorial illustration fused with limited-color screen print; large flat blocks, coarse dry-brush, broken edges, scraped pigment, halftone dots and paper grain; skyline lights are sparse irregular cream and pink dots, water reflections are interrupted horizontal dashes. Composition/framing: 4:5 portrait, bold circular foreground anchor, low horizon, expansive sky, a simple horizontal rhythm. Lighting/mood: coral sunset sliding into indigo, slow ferry, relaxed and cinematic. Color palette: cobalt, ultramarine, violet, coral orange, cream, muted teal. Constraints: Shanghai atmosphere without a Bund panorama or dense landmark inventory. Avoid: photorealistic water, detailed skyline, smooth gradients, readable ferry text, logos, watermark, 3D, cyberpunk, collage, or exact reference copying.",
  "image": "images/r6-04/citypop-shanghai-04.png",
  "aspect": "portrait",
  "variant": null,
  "city": "上海"
},
{
  "id": "r6-05",
  "sourceId": "r6-05",
  "round": "round6",
  "roundLabel": "06 / 参考规律",
  "title": "陆家嘴屋顶泳池切片",
  "prompt": "Use case: stylized-concept. Asset type: vertical web gallery artwork. Input images: Image 1, Image 2, Image 3 are reference images for brushwork, palette, composition and print texture only; do not copy their exact scenes or layouts. Primary request: 原创一幅上海陆家嘴屋顶泳池的4:5竖幅局部绘画，浅青蓝矩形泳池从画面底部向远处收缩，奶油白池畔形成强烈几何边线，前景一角露出珊瑚红折叠躺椅和一盆深绿植物，泳池后方只露出上海中心大厦和一座玻璃楼的上半段，不画完整CBD天际线。 Style/medium: rough hand-painted gouache and acrylic editorial illustration fused with limited-color screen print; broad flat blocks, coarse dry-brush, broken edges, scraped pigment, irregular halftone dots, paper fibers, slight ink misregistration; pool reflections are sparse cream dots and short strokes. Composition/framing: 4:5 portrait, low geometric perspective, pool leading line, open sky occupying the upper half, one small white cloud. Lighting/mood: bright late afternoon sliding toward lavender, cool water against warm architecture, relaxed city-resort fantasy. Color palette: turquoise, cobalt blue, deep indigo, coral red, cream, citrus yellow-green, a small magenta accent. Constraints: Shanghai landmark as a partial silhouette, no panorama, no people. Avoid: photorealism, glossy 3D pool, perfect architecture, smooth gradients, dense windows, readable signs, logos, watermark, cyberpunk, collage, or exact reference copying.",
  "image": "images/r6-05/citypop-shanghai-05.png",
  "aspect": "portrait",
  "variant": null,
  "city": "上海"
},
{
  "id": "r6-06",
  "sourceId": "r6-06",
  "round": "round6",
  "roundLabel": "06 / 参考规律",
  "title": "朱家角水巷的白墙",
  "prompt": "Use case: stylized-concept. Asset type: vertical web gallery artwork. Input images: Image 1, Image 2, Image 3 are reference images for brushwork, palette, composition and print texture only; do not copy their exact scenes or layouts. Primary request: 原创一幅上海朱家角水乡的4:5竖幅局部绘画，前景右侧是一座石桥栏板和一小簇荷叶，左侧露出白墙黑瓦民居的一角，窄窄的河道向远处消失，水面只留少量暖黄色和珊瑚粉点光，桥后可有一盏孤灯，不画完整古镇全景；上方保留大面积青蓝到紫粉的天空。 Style/medium: rough hand-painted gouache and acrylic editorial illustration fused with limited-color screen print; simplified architectural planes, coarse dry-brush, broken roof edges, scraped pigment, irregular halftone dots, paper fibers, slight misregistration; water is made from uneven horizontal dashes and broken color patches. Composition/framing: 4:5 portrait, bridge railing as a near foreground crop, diagonal canal leading line, large quiet sky, one hanging branch at the top edge. Lighting/mood: humid summer evening, soft breeze, nostalgic but not picturesque-perfect. Color palette: ultramarine, turquoise, violet, coral pink, warm cream, deep green, a touch of vermilion. Constraints: unmistakably Jiangnan Shanghai outskirts, original local fragment, no full tourist postcard. Avoid: photorealism, detailed tiles, smooth digital gradients, crowds, boats with text, readable signs, logos, watermark, 3D, cyberpunk, collage, or exact reference recreation.",
  "image": "images/r6-06/citypop-shanghai-06.png",
  "aspect": "portrait",
  "variant": null,
  "city": "上海"
},
{
  "id": "r6-07",
  "sourceId": "r6-07",
  "round": "round6",
  "roundLabel": "06 / 参考规律",
  "title": "杨浦大桥的斜向电缆",
  "prompt": "Use case: stylized-concept. Asset type: vertical web gallery artwork. Input images: Image 1, Image 2, Image 3 are reference images for brushwork, palette, composition and print texture only; do not copy their exact scenes or layouts. Primary request: 原创一幅上海杨浦大桥的4:5竖幅局部绘画，画面右下到左上被一根粗大的深蓝桥缆和几段橙色灯带斜切，前景左侧只有一小簇被风吹动的树叶，远处黄浦江与低矮城市被压缩成深靛蓝横向色带，杨浦大桥塔身只出现一段，不画完整大桥全景；天空占上方三分之二，可留一条极细飞机航迹。 Style/medium: rough hand-painted gouache and acrylic editorial illustration fused with limited-color screen print; hard-edged silhouettes mixed with coarse dry-brush, broken paint, scraped pigment, halftone dots, paper fibers and slight ink misregistration; bridge lights and river reflections are sparse handmade dots and short dashes. Composition/framing: 4:5 portrait, one dominant diagonal, asymmetrical negative space, low horizon, no centered postcard balance. Lighting/mood: blue hour with coral horizon, wind and movement, calm urban music-cover atmosphere. Color palette: cobalt, midnight navy, violet, magenta, coral orange, cream yellow, muted green. Constraints: the bridge fragment must read as Shanghai while remaining graphic and simplified. Avoid: engineering precision, photorealism, smooth gradients, excessive neon, readable road signs, logos, watermark, 3D, cyberpunk, collage, or exact reference copying.",
  "image": "images/r6-07/citypop-shanghai-07.png",
  "aspect": "portrait",
  "variant": null,
  "city": "上海"
},
{
  "id": "r6-08",
  "sourceId": "r6-08",
  "round": "round6",
  "roundLabel": "06 / 参考规律",
  "title": "复兴公园门框与珊瑚车",
  "prompt": "Use case: stylized-concept. Asset type: vertical web gallery artwork. Input images: Image 1, Image 2, Image 3 are reference images for brushwork, palette, composition and print texture only; do not copy their exact scenes or layouts. Primary request: 原创一幅上海复兴公园边缘街角的4:5竖幅绘画，前景下方只露出一辆珊瑚橙复古敞篷车的车头和圆形后视镜，车后是深绿树篱与一扇公园铁门的局部，左上伸出一枝开着小花的梧桐或玉兰，远处只露出一小块米色老公寓立面，不画完整街道。 Style/medium: rough hand-painted gouache and acrylic editorial illustration fused with limited-color screen print; flat color fields, thick dry-brush, uneven edges, scraped pigment, irregular halftone dots, paper fibers and slight misregistration; chrome highlights are limited to a few cream strokes, not glossy realism. Composition/framing: 4:5 portrait, car crop anchors the bottom edge, foliage frames the upper corner, broad blue sky and one flat cloud, layered silhouettes. Lighting/mood: warm summer late afternoon, languid, intimate, quietly glamorous. Color palette: deep green, cobalt, cerulean, coral orange, brick red, cream, a small violet shadow. Constraints: Shanghai park atmosphere, local fragment, no identifiable brand or readable text. Avoid: photorealism, detailed car logo, shiny 3D, smooth gradients, people, signs, watermark, cyberpunk, collage, or exact reference recreation.",
  "image": "images/r6-08/citypop-shanghai-08.png",
  "aspect": "portrait",
  "variant": null,
  "city": "上海"
},
{
  "id": "r6-09",
  "sourceId": "r6-09",
  "round": "round6",
  "roundLabel": "06 / 参考规律",
  "title": "老公寓阳台的月色",
  "prompt": "Use case: stylized-concept. Asset type: vertical web gallery artwork. Input images: Image 1, Image 2, Image 3 are reference images for brushwork, palette, composition and print texture only; do not copy their exact scenes or layouts. Primary request: 原创一幅上海老公寓阳台的4:5竖幅夜景绘画，前景是深靛蓝色阳台栏杆、一个陶土花盆和一片被风吹动的棕榈叶或龟背竹，右上是一轮极简奶油白月亮，远处只露出几栋上海老公寓与一根小小东方明珠线条，窗灯用疏密变化的暖黄色点点表示，不画完整城市全景。 Style/medium: rough hand-painted gouache and acrylic editorial illustration fused with limited-color screen print; broad flat night shapes, coarse dry-brush, broken edges, scraped pigment, irregular halftone dots, paper fibers, slight ink misregistration; moonlight and windows are simple dots and short marks, not photorealistic glow. Composition/framing: 4:5 portrait, railing anchors the bottom edge, plant frames one corner, large open midnight-blue sky, quiet asymmetrical balance. Lighting/mood: humid Shanghai summer night, intimate, slow, a little dreamy. Color palette: midnight navy, cobalt, violet, magenta plum, coral pink, cream yellow, muted leaf green. Constraints: original local balcony fragment with Shanghai identity, rough hand-made surface. Avoid: photorealism, glossy rendering, smooth gradients, detailed windows, people, readable signs, logos, watermark, 3D, cyberpunk, collage, or exact reference copying.",
  "image": "images/r6-09/citypop-shanghai-09.png",
  "aspect": "portrait",
  "variant": null,
  "city": "上海"
},
{
  "id": "r6-10",
  "sourceId": "r6-10",
  "round": "round6",
  "roundLabel": "06 / 参考规律",
  "title": "外白渡桥栏杆的余晖",
  "prompt": "Use case: stylized-concept. Asset type: vertical web gallery artwork. Input images: Image 1, Image 2, Image 3 are reference images for brushwork, palette, composition and print texture only; do not copy their exact scenes or layouts. Primary request: 原创一幅上海外白渡桥的4:5竖幅局部绘画，只取前景一段深蓝铸铁栏杆和桥面边缘，栏杆形成向远处收缩的强烈对角线；背景是黄浦江、低矮岸线与一小段被压缩的高楼轮廓，东方明珠只作为远处一颗细小的红色或暖黄亮点，天空留出大面积青蓝、紫罗兰与珊瑚橙，悬着一朵扁平白云，不画外滩全景。 Style/medium: rough hand-painted gouache and acrylic editorial illustration fused with limited-color screen print; bold flat silhouettes, coarse dry-brush, scraped paint, broken edges, irregular halftone dots, visible paper fibers and slight misregistration; river lights and reflections are sparse hand-placed dots and broken horizontal dashes. Composition/framing: 4:5 portrait, dominant diagonal railing, low horizon, large negative sky, one small landmark anchor. Lighting/mood: final warm light before blue hour, breezy, spacious, nostalgic city-cover feeling. Color palette: cerulean, cobalt, violet, coral orange, deep navy, cream, a few red and citrus marks. Constraints: recognizable Shanghai bridge fragment, graphic simplification, no exact reference scene. Avoid: photorealism, engineering detail, smooth AI gradients, dense skyline, readable plaques, logos, watermark, 3D, cyberpunk, collage, or artist imitation.",
  "image": "images/r6-10/citypop-shanghai-10.png",
  "aspect": "portrait",
  "variant": null,
  "city": "上海"
}
];
